name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t stijn0vp/linktree:latest .

    - name: Push Docker image to Docker Hub
      run: docker push stijn0vp/linktree:latest

  deploy:
    runs-on: [self-hosted]
    needs: build 

    steps:
    - name: Deploy container
      run: |
        docker stop linktree || true
        docker rm linktree || true
        docker image rm stijn0vp/linktree:latest
        docker pull stijn0vp/linktree:latest
        docker run -d -p 8081:80 --name linktree stijn0vp/linktree:latest